# Configuração global
global:
  backup_base_dir: /opt/backup
  log_dir: /var/log
  notification:
    enabled: false
    # Método de notificação: email, slack, teams, none
    method: email
    email:
      recipient: ti_altaneiro@altaneiro.com.br
    # Adicione configurações para outros métodos se necessário

# Configurações de retenção padrão
default_retention:
  weekly: 5      # número de backups semanais a manter

# Lista de VMs para backup
vms:
  # Windows Server com AD
  - name: winserver2022
    enabled: true
    description: "Windows Server 2022 com Active Directory"
    vm_file: /var/lib/libvirt/images/win2022.qcow2
    backup_types:
      - type: offline
        enabled: true
        schedule: "weekly" # referência para uso com crontab
        retention_count: 4 # sobrescreve o padrão, se necessário
        shutdown_timeout: 600 # tempo em segundos para aguardar desligamento

  # Snipe-IT
  - name: VMSnipeit
    enabled: true
    description: "Snipe-IT on Ubuntu Server LTS" 
    vm_file: /var/lib/libvirt/images/VMSnipeit.qcow2
    backup_types:
      - type: offline
        enabled: true
        schedule: "weekly"
        retention_count: 4
        shutdown_timeout: 600

  # Unifi
  - name: vmunifi
    enabled: true
    description: "Unifi on Ubuntu Server LTS"
    vm_file: /var/lib/libvirt/images/vmunifi.qcow2
    backup_types:
      - type: offline
        enabled: true
        schedule: "weekly"
        retention_count: 4
        shutdown_timeout: 600

  # Dimep - Windows 10
  - name: win10Dimep
    enabled: true
    description: "Windows 10 com serviço Dimep"
    vm_file: /var/lib/libvirt/images/win10-dimep.qcom2
    backup_types:
      - type: offline
        enabled: true
        schedule: "weekly"
        retention_count: 4
        shutdown_timeout: 600
