# Configuração global
global:
  backup_base_dir: /opt/backup
  log_dir: /var/log
  notification:
    enabled: false
    # Método de notificação: email, slack, teams, none
    method: email
    email:
      recipient: admin@example.com
    # Adicione configurações para outros métodos se necessário

# Configurações de retenção padrão
default_retention:
  checkpoint: 7  # dias para manter checkpoints
  weekly: 8      # número de backups semanais a manter

# Lista de VMs para backup
vms:
  # Windows Server com AD
  - name: winserver2022
    enabled: false
    description: "Windows Server 2022 com Active Directory"
    vm_file: /var/lib/libvirt/images/win2022.qcow2
    backup_types:
      - type: checkpoint
        enabled: true
        schedule: "daily"  # pode ser usado com crontab
        retention_days: 7  # sobrescreve o padrão, se necessário
        special_options:
          keep_ram: true   # opções específicas para este tipo de backup
      - type: offline
        enabled: true
        schedule: "weekly" # pode ser usado com crontab
        retention_count: 8 # sobrescreve o padrão, se necessário
        shutdown_timeout: 600
        special_options:
          keep_last_checkpoint: false

  # Snipe-IT
  - name: VMSnipeit
    enabled: true
    description: "Snipe-IT on Ubuntu Server LTS" 
    vm_file: /var/lib/libvirt/images/VMSnipeit.qcow2
    backup_types:
      - type: checkpoint
        enabled: true
        schedule: "daily"
      - type: offline
        enabled: true
        schedule: "weekly" # pode ser usado com crontab
        retention_count: 8 # sobrescreve o padrão, se necessário
        shutdown_timeout: 600
        special_options:
          keep_last_checkpoint: false
